name: Codecov Coverage
run-name: codecov-coverage


on:
  pull_request:
    branches:
      - main


jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Report
        id: coverage-report
        continue-on-error: true
        run: |
          pip install pytest pytest-cov
          pytest --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        id: codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml